// Clash Detection Result Sample Data

export const jsonData = {
  clashDetectionResult: [{
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000010",
    elementALabel: "IsmCurveMember [4-G]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000003e",
    elementBLabel: "IsmCurveMember [4-1Q]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000010",
    elementALabel: "IsmCurveMember [4-G]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000044",
    elementBLabel: "IsmCurveMember [4-1W]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000010",
    elementALabel: "IsmCurveMember [4-G]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000045",
    elementBLabel: "IsmCurveMember [4-1X]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000010",
    elementALabel: "IsmCurveMember [4-G]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000046",
    elementBLabel: "IsmCurveMember [4-1Y]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000012",
    elementALabel: "IsmCurveMember [4-I]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000040",
    elementBLabel: "IsmCurveMember [4-1S]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000012",
    elementALabel: "IsmCurveMember [4-I]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000043",
    elementBLabel: "IsmCurveMember [4-1V]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000012",
    elementALabel: "IsmCurveMember [4-I]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000044",
    elementBLabel: "IsmCurveMember [4-1W]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000012",
    elementALabel: "IsmCurveMember [4-I]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000045",
    elementBLabel: "IsmCurveMember [4-1X]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000012",
    elementALabel: "IsmCurveMember [4-I]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000046",
    elementBLabel: "IsmCurveMember [4-1Y]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000013",
    elementALabel: "IsmCurveMember [4-J]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000003e",
    elementBLabel: "IsmCurveMember [4-1Q]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000013",
    elementALabel: "IsmCurveMember [4-J]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000041",
    elementBLabel: "IsmCurveMember [4-1T]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000013",
    elementALabel: "IsmCurveMember [4-J]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000047",
    elementBLabel: "IsmCurveMember [4-1Z]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000013",
    elementALabel: "IsmCurveMember [4-J]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000048",
    elementBLabel: "IsmCurveMember [4-20]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000013",
    elementALabel: "IsmCurveMember [4-J]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000049",
    elementBLabel: "IsmCurveMember [4-21]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000014",
    elementALabel: "IsmCurveMember [4-K]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000040",
    elementBLabel: "IsmCurveMember [4-1S]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000014",
    elementALabel: "IsmCurveMember [4-K]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000042",
    elementBLabel: "IsmCurveMember [4-1U]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000016",
    elementALabel: "IsmCurveMember [4-M]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000040",
    elementBLabel: "IsmCurveMember [4-1S]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000016",
    elementALabel: "IsmCurveMember [4-M]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000042",
    elementBLabel: "IsmCurveMember [4-1U]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000017",
    elementALabel: "IsmCurveMember [4-N]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000004d",
    elementBLabel: "IsmCurveMember [4-25]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000017",
    elementALabel: "IsmCurveMember [4-N]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000004e",
    elementBLabel: "IsmCurveMember [4-26]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000017",
    elementALabel: "IsmCurveMember [4-N]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000004f",
    elementBLabel: "IsmCurveMember [4-27]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000018",
    elementALabel: "IsmCurveMember [4-O]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000040",
    elementBLabel: "IsmCurveMember [4-1S]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000018",
    elementALabel: "IsmCurveMember [4-O]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000042",
    elementBLabel: "IsmCurveMember [4-1U]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000018",
    elementALabel: "IsmCurveMember [4-O]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000043",
    elementBLabel: "IsmCurveMember [4-1V]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000018",
    elementALabel: "IsmCurveMember [4-O]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000004f",
    elementBLabel: "IsmCurveMember [4-27]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000019",
    elementALabel: "IsmCurveMember [4-P]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000003e",
    elementBLabel: "IsmCurveMember [4-1Q]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000019",
    elementALabel: "IsmCurveMember [4-P]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000041",
    elementBLabel: "IsmCurveMember [4-1T]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000019",
    elementALabel: "IsmCurveMember [4-P]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000050",
    elementBLabel: "IsmCurveMember [4-28]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000019",
    elementALabel: "IsmCurveMember [4-P]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000051",
    elementBLabel: "IsmCurveMember [4-29]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000019",
    elementALabel: "IsmCurveMember [4-P]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000052",
    elementBLabel: "IsmCurveMember [4-2A]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001a",
    elementALabel: "IsmCurveMember [4-Q]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000040",
    elementBLabel: "IsmCurveMember [4-1S]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001a",
    elementALabel: "IsmCurveMember [4-Q]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000042",
    elementBLabel: "IsmCurveMember [4-1U]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001a",
    elementALabel: "IsmCurveMember [4-Q]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000043",
    elementBLabel: "IsmCurveMember [4-1V]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001a",
    elementALabel: "IsmCurveMember [4-Q]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000050",
    elementBLabel: "IsmCurveMember [4-28]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001a",
    elementALabel: "IsmCurveMember [4-Q]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000051",
    elementBLabel: "IsmCurveMember [4-29]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001a",
    elementALabel: "IsmCurveMember [4-Q]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000052",
    elementBLabel: "IsmCurveMember [4-2A]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001b",
    elementALabel: "IsmCurveMember [4-R]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000038",
    elementBLabel: "IsmCurveMember [4-1K]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001b",
    elementALabel: "IsmCurveMember [4-R]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000003a",
    elementBLabel: "IsmCurveMember [4-1M]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001b",
    elementALabel: "IsmCurveMember [4-R]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000005a",
    elementBLabel: "IsmCurveMember [4-2I]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001b",
    elementALabel: "IsmCurveMember [4-R]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000005b",
    elementBLabel: "IsmCurveMember [4-2J]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001c",
    elementALabel: "IsmCurveMember [4-S]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000039",
    elementBLabel: "IsmCurveMember [4-1L]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001c",
    elementALabel: "IsmCurveMember [4-S]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000003a",
    elementBLabel: "IsmCurveMember [4-1M]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001c",
    elementALabel: "IsmCurveMember [4-S]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000005a",
    elementBLabel: "IsmCurveMember [4-2I]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001c",
    elementALabel: "IsmCurveMember [4-S]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000005b",
    elementBLabel: "IsmCurveMember [4-2J]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001d",
    elementALabel: "IsmCurveMember [4-T]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000029",
    elementBLabel: "IsmCurveMember [4-15]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001d",
    elementALabel: "IsmCurveMember [4-T]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000054",
    elementBLabel: "IsmCurveMember [4-2C]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001d",
    elementALabel: "IsmCurveMember [4-T]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000055",
    elementBLabel: "IsmCurveMember [4-2D]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001d",
    elementALabel: "IsmCurveMember [4-T]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000059",
    elementBLabel: "IsmCurveMember [4-2H]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001d",
    elementALabel: "IsmCurveMember [4-T]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000097",
    elementBLabel: "IsmSurfaceMember [4-47]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001e",
    elementALabel: "IsmCurveMember [4-U]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000027",
    elementBLabel: "IsmCurveMember [4-13]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001e",
    elementALabel: "IsmCurveMember [4-U]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000053",
    elementBLabel: "IsmCurveMember [4-2B]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001e",
    elementALabel: "IsmCurveMember [4-U]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000054",
    elementBLabel: "IsmCurveMember [4-2C]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001e",
    elementALabel: "IsmCurveMember [4-U]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000059",
    elementBLabel: "IsmCurveMember [4-2H]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001e",
    elementALabel: "IsmCurveMember [4-U]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000098",
    elementBLabel: "IsmSurfaceMember [4-48]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001f",
    elementALabel: "IsmCurveMember [4-V]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000029",
    elementBLabel: "IsmCurveMember [4-15]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001f",
    elementALabel: "IsmCurveMember [4-V]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x4000000003c",
    elementBLabel: "IsmCurveMember [4-1O]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000001f",
    elementALabel: "IsmCurveMember [4-V]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000055",
    elementBLabel: "IsmCurveMember [4-2D]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000054",
    elementALabel: "IsmCurveMember [4-2C]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000055",
    elementBLabel: "IsmCurveMember [4-2D]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x40000000055",
    elementALabel: "IsmCurveMember [4-2D]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000056",
    elementBLabel: "IsmCurveMember [4-2E]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  },
  {
    clashType: "Collision",
    clearance: -1,
    elementAId: "0x4000000005f",
    elementALabel: "IsmCurveMember [4-2N]",
    elementACategoryIndex: 0,
    elementAModelIndex: 0,
    elementBId: "0x40000000070",
    elementBLabel: "IsmCurveMember [4-34]",
    elementBCategoryIndex: 0,
    elementBModelIndex: 0,
  }],
  categoryList: [{
    id: "0x4000000000d",
    displayName: "Tag-Category",
  },
  {
    id: "0x40000000e71",
    displayName: "Structure",
  },
  {
    id: "0x40000000eba",
    displayName: "E-HEX",
  },
  {
    id: "0x40000000edd",
    displayName: "PipeSupport",
  }],
  modelList: [{
    id: "0x20000000002",
    displayName: "BayTown",
  }],
};
